### ISSUE TITLE
Error loading custom driver UI: scaleway

### ISSUE THREAD

**Issue by lecler-i** [mitcdh/ui-driver-scaleway#4]
Hello,

I just setup the custom driver on my Rancher, after adding my first host, it doent work anymore...

`
Error loading custom driver UI: scaleway
Reload to try again or log out
`

[logs.txt](https://github.com/mitcdh/ui-driver-scaleway/files/1150547/logs.txt)

**Comment by mitcdh** [comment]
Well it looks like the default cert that is being returned from the server github.io without [SNI](https://en.wikipedia.org/wiki/Server_Name_Indication) is now only valid for opensource.guide. For example:

### With SNI
````
$ openssl s_client -servername mitcdh.github.io -connect mitcdh.github.io:443 2>/dev/null | openssl x509 -noout -text | grep DNS
                DNS:www.github.com, DNS:*.github.com, DNS:github.com, DNS:*.github.io, DNS:github.io, DNS:*.githubusercontent.com, DNS:githubusercontent.com
````

### Without SNI

````
$ openssl s_client  -connect mitcdh.github.io:443 2>/dev/null | openssl x509 -noout -text | grep DNS
                DNS:opensource.guide, DNS:www.opensource.guide
````

This becomes a problem as the Apache HTTP Client library included with rancher doesn't seem to support SNI. I believe this would be a larger problem and will hopefully be fixed by the nice people at GitHub in time.

I'll host the current files somewhere else later today but if you're willing to use plain http I believe that would function correctly for now, although I haven't tested it.

**Comment by mitcdh** [comment]
#5 

Should be fixed with the rawgit url: https://cdn.rawgit.com/mitcdh/ui-driver-scaleway/master/dist/component.js

Also updating readme to reflect this.
